x-envs: &envs
  env_file: .env
  environment:
    - FLASK_APP=pypistats/run.py
    - FLASK_ENV=development
    - FLASK_DEBUG=1
    - DATABASE_URL=${DATABASE_URL:-postgresql://admin:root@postgresql:5432/pypistats}
    - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    - BASIC_AUTH_USER=${BASIC_AUTH_USER:-user}
    - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-password}
    - PYPISTATS_SECRET=${PYPISTATS_SECRET:-dev-secret-key}
    - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON:-}

version: "3.4"

volumes:
  pgdata: {}

services:
  web:
    build:
      context: .
    image: web
    command: webdev
    depends_on:
      - postgresql
    <<: *envs
    ports:
      - "8000:5000"
    volumes:
      - "./pypistats/:/app/pypistats/"
  beat:
    image: web
    command: beat
    depends_on:
      - redis
    <<: *envs
    volumes:
      - "./pypistats/:/app/pypistats/"
  celery:
    image: web
    command: celery
    depends_on:
      - redis
      - postgresql
    <<: *envs
    volumes:
      - "./pypistats/:/app/pypistats/"
  flower:
    image: web
    command: flower
    depends_on:
      - redis
    <<: *envs
    ports:
      - "5555:5555"
    volumes:
      - "./pypistats/:/app/pypistats/"
  migrate:
    image: web
    command: migrate
    depends_on:
      - postgresql
    <<: *envs
    volumes:
      - "./pypistats/:/app/pypistats/"
      - "./migrations/:/app/migrations/"
  seeds:
    image: web
    command: seeds
    depends_on:
      - postgresql
      - migrate
    <<: *envs
    volumes:
      - "./pypistats/:/app/pypistats/"
      - "./migrations/:/app/migrations/"
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
  postgresql:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pypistats
    ports:
      - "5433:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
