version: "3"

volumes:
  pgdata: {}

services:
  web:
    build:
      context: .
    command: webdev
    depends_on:
      - postgresql
    environment:
      - FLASK_APP=pypistats/run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DBNAME=pypistats
      - CELERY_BROKER_URL=redis://redis
    ports:
      - "5000:5000"
    volumes:
      - "./pypistats/:/app/pypistats/"
  beat:
    build:
      context: .
    command: beat
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis
    volumes:
      - "./pypistats/:/app/pypistats/"
  celery:
    build:
      context: .
    command: celery
    depends_on:
      - redis
      - postgresql
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DBNAME=pypistats
      - CELERY_BROKER_URL=redis://redis
    volumes:
      - "./pypistats/:/app/pypistats/"
  flower:
    build:
      context: .
    command: flower
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis
    ports:
      - "5555:5555"
    volumes:
      - "./pypistats/:/app/pypistats/"
  migrate:
    build:
      context: .
    command: migrate
    depends_on:
      - postgresql
    environment:
      - FLASK_APP=pypistats/run.py
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DBNAME=pypistats
    volumes:
      - "./pypistats/:/app/pypistats/"
      - "./migrations/:/app/migrations/"
  seeds:
    build:
      context: .
    command: seeds
    depends_on:
      - postgresql
      - migrate
    environment:
      - FLASK_APP=pypistats/run.py
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DBNAME=pypistats
    volumes:
      - "./pypistats/:/app/pypistats/"
      - "./migrations/:/app/migrations/"
  redis:
    image: "redis:5.0.7-alpine"
    ports:
      - "6379:6379"
  postgresql:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pypistats
    ports:
      - "5433:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
