"""setup_tables

Revision ID: 0cf9945079f1
Revises: 
Create Date: 2020-03-03 22:17:51.438119

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0cf9945079f1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "overall",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_index(op.f("ix_overall_package"), "overall", ["package"], unique=False)
    op.create_table(
        "python_major",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=4), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_index(op.f("ix_python_major_package"), "python_major", ["package"], unique=False)
    op.create_table(
        "python_minor",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=4), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_index(op.f("ix_python_minor_package"), "python_minor", ["package"], unique=False)
    op.create_table(
        "recent",
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=8), nullable=False),
        sa.Column("downloads", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("package", "category"),
    )
    op.create_index(op.f("ix_recent_package"), "recent", ["package"], unique=False)
    op.create_table(
        "system",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=8), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_index(op.f("ix_system_package"), "system", ["package"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=39), nullable=False),
        sa.Column("avatar_url", sa.String(length=256), nullable=True),
        sa.Column("token", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("favorites", postgresql.ARRAY(sa.String(length=128), dimensions=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index(op.f("ix_system_package"), table_name="system")
    op.drop_table("system")
    op.drop_index(op.f("ix_recent_package"), table_name="recent")
    op.drop_table("recent")
    op.drop_index(op.f("ix_python_minor_package"), table_name="python_minor")
    op.drop_table("python_minor")
    op.drop_index(op.f("ix_python_major_package"), table_name="python_major")
    op.drop_table("python_major")
    op.drop_index(op.f("ix_overall_package"), table_name="overall")
    op.drop_table("overall")
    # ### end Alembic commands ###
