"""Change download columns from INTEGER to BIGINT

Revision ID: 50cca6fa7694
Revises: 0cf9945079f1
Create Date: 2025-08-14 18:06:27.352695

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50cca6fa7694"
down_revision = "0cf9945079f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change download columns from INTEGER to BIGINT to handle large values
    # Using direct ALTER TABLE commands to avoid batch mode issues
    op.execute("ALTER TABLE overall ALTER COLUMN downloads TYPE BIGINT")
    op.execute("ALTER TABLE python_major ALTER COLUMN downloads TYPE BIGINT")
    op.execute("ALTER TABLE python_minor ALTER COLUMN downloads TYPE BIGINT")
    op.execute("ALTER TABLE system ALTER COLUMN downloads TYPE BIGINT")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert download columns back to INTEGER (may fail if values > 2.1B)
    op.execute("ALTER TABLE system ALTER COLUMN downloads TYPE INTEGER")
    op.execute("ALTER TABLE python_minor ALTER COLUMN downloads TYPE INTEGER")
    op.execute("ALTER TABLE python_major ALTER COLUMN downloads TYPE INTEGER")
    op.execute("ALTER TABLE overall ALTER COLUMN downloads TYPE INTEGER")
    # ### end Alembic commands ###
