"""initial models

Revision ID: 9116cea0e0d7
Revises:
Create Date: 2018-04-04 23:48:49.351410

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9116cea0e0d7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "overall",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_table(
        "python_major",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=4), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_table(
        "python_minor",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=4), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_table(
        "recent",
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=8), nullable=False),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("package", "category"),
    )
    op.create_table(
        "system",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("package", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=8), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "package", "category"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=39), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("favorites", postgresql.ARRAY(sa.String(length=128), dimensions=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("system")
    op.drop_table("recent")
    op.drop_table("python_minor")
    op.drop_table("python_major")
    op.drop_table("overall")
    # ### end Alembic commands ###
