"""empty message

Revision ID: e65ba8f3cdcf
Revises: c81b3715b9e5
Create Date: 2018-04-06 17:58:19.643259

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e65ba8f3cdcf"
down_revision = "c81b3715b9e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("uid", sa.Integer(), nullable=True))
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["uid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.drop_column("users", "uid")
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
