apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: pypistats
  labels:
    app: pypistats
    component: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypistats
      component: flower
  template:
    metadata:
      labels:
        app: pypistats
        component: flower
    spec:
      containers:
      - name: pypistats-flower
        image: us.gcr.io/pypistats-org/pypistats:11
        imagePullPolicy: Always
        args: ["flower"]
        envFrom:
        - secretRef:
            name: pypistats-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    app: pypistats
    component: flower
spec:
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: pypistats
    component: flower
