apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  namespace: pypistats
  labels:
    app: pypistats
    component: tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypistats
      component: tasks
  template:
    metadata:
      labels:
        app: pypistats
        component: tasks
    spec:
      containers:
      - name: beat
        image: us.gcr.io/pypistats-org/pypistats:1
        imagePullPolicy: Always
        args: ["beat"]
        envFrom:
        - secretRef:
            name: pypistats-secrets
      - name: celery
        image: us.gcr.io/pypistats-org/pypistats:1
        imagePullPolicy: Always
        args: ["celery"]
        envFrom:
        - secretRef:
            name: pypistats-secrets
