apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: pypistats
  labels:
    app: pypistats
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pypistats
      component: web
  template:
    metadata:
      labels:
        app: pypistats
        component: web
    spec:
      initContainers:
      - name: migrate
        image: us.gcr.io/pypistats-org/pypistats:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: pypistats-secrets
        args: ["migrate"]
      containers:
      - name: web
        image: us.gcr.io/pypistats-org/pypistats:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: pypistats-secrets
        args: ["web"]
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: pypistats
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30500
  selector:
    app: pypistats
    component: web
